name: Deploy CDK Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          python3 -m venv lambda/cdk/.venv
          source lambda/cdk/.venv/bin/activate
          pip install --no-cache-dir -r lambda/cdk/requirements.txt
          npm install --prefix lambda/cdk aws-cdk

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::522519385494:role/github-actions
          aws-region: us-east-1

      - name: Pre-synth cleanup
        run: |
          rm -rf ~/.npm
          rm -rf ~/.cache/pip
          sudo rm -rf /usr/local/lib/node_modules

      - name: CDK Synth
        working-directory: lambda/cdk
        run: |
          source .venv/bin/activate
          npx cdk synth --app "python app.py"

      - name: CDK Deploy
        working-directory: lambda/cdk
        run: |
          npx cdk deploy --app "python app.py" -f

      - name: Final cleanup
        run: |
          rm -rf lambda/cdk/.venv
          rm -rf lambda/cdk/cdk.out
