name: Deploy to S3 (OIDC)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Node.js and dependencies
      uses: actions/setup-node@v4
      with: 
        node-version: 18

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install dependencies
      run: yarn install

    - name: Build the React app
      run: yarn build

    - name: Configure AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::522519385494:role/github-actions
        aws-region: us-east-1

    - name: Deploy to S3
      run: aws s3 sync dist/ s3://film.aryaneja.com --delete